pub enum SyncType {
    None = 0,
    BaseSPV = 1,
    FullBlocks = 1 << 1,
    Mempools = 1 << 2,
    SPV = SyncType::BaseSPV | SyncType::Mempools,
    MasternodeList = 1 << 3,
    VerifiedMasternodeList = SyncType::MasternodeList | SyncType::SPV,
    Governance = 1 << 4,
    GovernanceVotes = 1 << 5,
    GovernanceVoting = SyncType::Governance | SyncType::MasternodeList,
    Sporks = 1 << 6,
    BlockchainIdentities = 1 << 7,
    DPNS = 1 << 8,
    Dashpay = 1 << 9,
    MultiAccountAutoDiscovery = 1 << 10,
    Default = SyncType::SPV | SyncType::Mempools | SyncType::VerifiedMasternodeList | SyncType::Sporks | SyncType::BlockchainIdentities | SyncType::DPNS | SyncType::Dashpay | SyncType::MultiAccountAutoDiscovery,
    NeedsWalletSyncType = SyncType::BaseSPV | SyncType::FullBlocks,
    GetsNewBlocks = SyncType::SPV | SyncType::FullBlocks,
}
